### PR TITLE
LPS-149147 Remove petra-content, need to test for performance since we removed content caching

### PR DESCRIPTION
**Pull request by julschong**
Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
SubTask: [LPS-149147](https://issues.liferay.com/browse/LPS-149147)

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help us scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@julschong Please send it to core infra, then it will be in my review queue. 

Thanks.
Tina.

**Comment by julschong** [comment]
@GinsonRen 
Hi Ginson,
We are doing apps/petra clean up and are removing petra-content in this pull.
ContentUtil does some not very ideal caching Map and incomplete key so we figured we can try removing it.

Could you please help us test if this impact the performance much?

Thank you!

CC. @tinatian

**Comment by GinsonRen** [comment]
@julschong I will test this next week, thanks.

**Comment by GinsonRen** [comment]
@julschong @tinatian Here are the performance testing results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 52236 | 284 | -
LPS-149147 | - | 51676 | 269 | -1.07%

WC:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 68005 | 488 | -
LPS-149147 | - | 69293 | 411 | 1.89%

MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 11268 | 16.1 | -
LPS-149147 | - | 11285 | 15.8 | 0.15%

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 16798 | 89.2 | -
LPS-149147 | - | 16598 | 121 | -1.19%

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 29515 | 539 | -
LPS-149147 | - | 31059 | 307 | 5.23%

AP:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 01d49824 | 26944 | 407 | -
LPS-149147 | - | 25830 | 394 | -4.13%

**Comment by julschong** [comment]
@tinatian 
Hi Tina,
Looks like it has significant impact on blog login time (30% more). 
Should we continue to remove petra-content?

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Pull request closed without merging**
