### PR TITLE
LPS-148493 test portal-log4j

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
added .lfrbuild-app-server-lib and .lfrbuild-portal-pre

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:revelant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
pushed: put portal-log4j back to petra-boostrap

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help us scan the test result again just in case?
Thank you!

**Comment by catarineaguiar** [comment]
Hi @julschong, sorry the delay. The unit test `LibraryReferenceTest` had this failure:

```
[junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
    [junit] junit.framework.AssertionFailedError: util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-04/test-1-28/test-portal-acceptance-pullrequest(master)/2955/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
> Hi @julschong, sorry the delay. The unit test `LibraryReferenceTest` had this failure:
> 
> ```
> [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
>     [junit] util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
>     [junit] junit.framework.AssertionFailedError: util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
>     [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2022-04/test-1-28/test-portal-acceptance-pullrequest(master)/2955/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

@catarineaguiar 
Hi Catarine, I was able to replicate the error locally. but I think that error is not related to my pull.

> 
>     [junit] Testcase: testLibJarsInEclipse(com.liferay.portal.library.LibraryReferenceTest):    FAILED
>     [junit] .classpath is missing a reference to lib/portal/httpmime.jar
>     [junit] junit.framework.AssertionFailedError: .classpath is missing a reference to lib/portal/httpmime.jar
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testMissingJarReferences(LibraryReferenceTest.java:252)
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testLibJarsInEclipse(LibraryReferenceTest.java:168)
>     [junit] 
>     [junit] 
>     [junit] Testcase: testLibJarsInNetBeans(com.liferay.portal.library.LibraryReferenceTest):   FAILED
>     [junit] nbproject/project.properties is missing a reference to lib/portal/httpmime.jar
>     [junit] junit.framework.AssertionFailedError: nbproject/project.properties is missing a reference to lib/portal/httpmime.jar
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testMissingJarReferences(LibraryReferenceTest.java:252)
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testLibJarsInNetBeans(LibraryReferenceTest.java:173)
>     [junit] 
>     [junit] 
>     [junit] Testcase: testLibJarsInVersions(com.liferay.portal.library.LibraryReferenceTest):   FAILED
>     [junit] lib/versions.xml is missing a reference to lib/portal/httpmime.jar
>     [junit] junit.framework.AssertionFailedError: lib/versions.xml is missing a reference to lib/portal/httpmime.jar
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testMissingJarReferences(LibraryReferenceTest.java:252)
>     [junit]     at com.liferay.portal.library.LibraryReferenceTest.testLibJarsInVersions(LibraryReferenceTest.java:178)
>

**Comment by vicnate5** [comment]
@julschong I am able to reproduce the unit test issue that matches the CI log (not the log you printed) and it looks related.

```
vicnate5@vicnate5-NUC10i7FNK:/opt/dev/projects/github/liferay-portal/portal-kernel (master-juls-334) $ ant test-class -Dtest.class=LibraryReferenceTest
Buildfile: /opt/dev/projects/github/liferay-portal/portal-kernel/build.xml
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null190707727.properties

init-compile:

compile:

test-class:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/portal-kernel/test-results/unit
     [copy] Copying 8 files to /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [javac] Compiling 156 source files to /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [javac] Note: /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/util/TextFormatterTest.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [echo] test.cmd.start.timestamp: 05-02-2022 16:15:11:611 PDT
    [junit] Running com.liferay.portal.library.LibraryReferenceTest
    [junit] Testsuite: com.liferay.portal.library.LibraryReferenceTest
    [junit] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.432 sec
    [junit] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.432 sec
    [junit]
    [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):       FAILED
    [junit] util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
    [junit] junit.framework.AssertionFailedError: util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-log4j]
    [junit]     at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
    [junit]
    [junit]
    [junit] Test com.liferay.portal.library.LibraryReferenceTest FAILED
[stopwatch] [test.cmd: 3.952 sec]
```

There is also an issue in the test results with Wildfly and Jboss, but I wasn't able to reproduce locally. Gonna run the environment specific testing here to confirm if it is an issue.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:app-servers

**Comment by vicnate5** [comment]
@julschong App servers are good, so just the unit test issue remains.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by catarineaguiar** [comment]
just started reviewing :)

**Comment by catarineaguiar** [comment]
@julschong no regressions were found.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
most test were aborted, I'll re-run the relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
weird stuff going on, I might rebase and try again

**Comment by julschong** [comment]
rebased and pushed to test again

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong a regression found:

`LibraryReferenceTest`
```
  [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] portal-impl/portal-impl.iml is missing orderEntry elements for modules [portal-log4j]
    [junit] junit.framework.AssertionFailedError: portal-impl/portal-impl.iml is missing orderEntry elements for modules [portal-log4j]
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-31/test-portal-acceptance-pullrequest(master)/3746/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
I cannot commit these .iml for some reason @@

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
fix LibraryReferenceTest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
@julschong No regressions found on new results.

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me scan this test result?
Thank you!

**Comment by julschong** [comment]
This pull has some issues that need resolved

**Pull request closed without merging**
