### PR TITLE
LPP-58824 protobuf try testing

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:24847504

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:report:27231145

**Comment by julschong** [comment]
ci:test:relevant

**Pull request closed without merging**
