### PR TITLE
LPD-37253 test functional

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:smoke

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
ci:test:upstream-dxp:dryrun

**Comment by julschong** [comment]
ci:report:24912296

**Comment by vicnate5** [comment]
Smoke test running with default runtimes switched to JDK21

**Pull request closed without merging**
