### PR TITLE
LPS-151632 test portal-portlet-url-builder

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
looks like many tests aborted @@
could you please help me scan this one?
Thank you!

**Comment by catarineaguiar** [comment]
Hey @julschong I found regressions:

```
[java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/definitions/display/context/ObjectDefinitionsValidationsDisplayContext.java expected:<... com.liferay.portal.[kernel.exception.PortalException;
     [java] import com.liferay.portal.kernel.json.JSONObject;
     [java] import com.liferay.portal.kernel.json.JSONUtil;
     [java] import com.liferay.portal.kernel.language.LanguageUtil;
     [java] import com.liferay.portal.kernel.portlet.LiferayWindowState;
     [java] import com.liferay.portal.kernel.security.permission.resource.ModelResourcePermission;
     [java] import com.liferay.portal.kernel.util.HashMapBuilder;
     [java] import com.liferay.portal.portlet.url.builder.PortletURL]Builder;
     [java] 
     [java] import jav...> but was:<... com.liferay.portal.[portlet.url.builder.PortletURLBuilder;
     [java] import com.liferay.portal.kernel.exception.PortalException;
     [java] import com.liferay.portal.kernel.json.JSONObject;
     [java] import com.liferay.portal.kernel.json.JSONUtil;
     [java] import com.liferay.portal.kernel.language.LanguageUtil;
     [java] import com.liferay.portal.kernel.portlet.LiferayWindowState;
     [java] import com.liferay.portal.kernel.security.permission.resource.ModelResourcePermission;
     [java] import com.liferay.portal.kernel.util.HashMap]Builder;
     [java] 
     [java] import jav...>
```
Full log: [here](https://testray.liferay.com/reports/production/logs/2022-04/test-1-25/test-portal-acceptance-pullrequest(master)/2485/source-format-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

and the other one you can run the Unit Test `LibraryReferenceTest` locally to confirm:

```
[junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-portlet-url-builder]
    [junit] junit.framework.AssertionFailedError: util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-portlet-url-builder]
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
```
Full log: [here](https://testray.liferay.com/reports/production/logs/2022-04/test-1-25/test-portal-acceptance-pullrequest(master)/2485/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
rebased and force push

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
fixed dependency and pushed

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Pull request closed without merging**
