### PR TITLE
LPS-142279 Refactor ClassUtil & PortalClassPathUtil to reuse common logic

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan the result?
Thank you!

**Comment by kyle-miho** [comment]
looking through this now

**Comment by kyle-miho** [comment]
@julschong this is the only unique error
`
    [junit] [Whip] com.liferay.portal.kernel.util.ClassUtil is not fully covered.
    [junit] [Whip]Branch coverage rate : 0.99, line coverage rate : 0.99.
    [junit] [Whip] com.liferay.portal.kernel.util.ClassUtil line 159 is not covered 
    [junit] [Whip] com.liferay.portal.kernel.util.ClassUtil line 160 is not covered 
    [junit] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.493 sec
    [junit] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.493 sec
    [junit] 
    [junit] Testcase: com.liferay.portal.kernel.util.ClassUtilTest:	FAILED
    [junit] com.liferay.portal.kernel.util.ClassUtil is not fully covered
    [junit] junit.framework.AssertionFailedError: com.liferay.portal.kernel.util.ClassUtil is not fully covered
    [junit] 	at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
    [junit] 	at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:66)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:119)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:84)`

**Comment by julschong** [comment]
@tinatian Hi Tina,
Kyle helped me scan the results. 
ClassUtil code coverage is the only failure now. 
I was trying to cover as much as possible. But, I did not know how to get to this part of getParentDir() which is not covered portion of ClassUtil
		**_if (pos == -1) {
			pos = path.lastIndexOf(".jar/");
		}_**

**Pull request closed without merging**
