### PR TITLE
LPS-142696 Fix XXE vulnerability in WSDDMerger

### PR DESCRIPTION
**Pull request by Seiphon**
Hey @julschong , according to ticket [LPS-142696](https://issues.liferay.com/browse/LPS-142696), we need to prevent the `XXE vulnerability`. But since the [LPS-145555](https://issues.liferay.com/browse/LPS-145555), the wsdd only used in old branches, could you please help to reveiw the changes and test the older branches? thanks!

### CODE REVIEW

**Comment by julschong** [comment]
@dantewang Hi Dante, have we looked at this issue before?
per @tinatian, we might have already reviewed this and maybed handled this another way

**Comment by dantewang** [comment]
@julschong I only remember that some of the third-party xml libraries we use don't recognize these properties...

**Comment by Seiphon** [comment]
OK, thank you guys, if this issue has been fixed, I gonna close this ticket.

**Comment by dantewang** [comment]
@Seiphon I'm not sure whether the fix is really in 7.3.x or prior.

**Comment by Seiphon** [comment]
@dantewang oh, I see, thanks. @julschong I found the old branches are still using wsdd-builder, and SAXReader is used in wsdd-builder, so maybe we should still need to fix it.

**Comment by julschong** [comment]
@dantewang 
got it, I'll let Tina know.

@Seiphon 
Just have a another question.
Does this only affect WSDDBuilder? I just did a search in our codebase and found several SAXReader usages that looks the same. does this mean that they should also have this fix?
image

**Comment by Seiphon** [comment]
Hey @julschong , in some situation, it may make sence to allow XXE. And there may also be other tickets created by Security team for other XXE. So we don't need to worry about that.

**Comment by julschong** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4031

**Pull request closed without merging**
