### PR TITLE
[CLDR TEST] LPD-18594 Fix CPCommerceWarehouseAndInventoryPermissions functional tests with CLDR

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:Sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
