### PR TITLE
LPS-152502 test refactor HttpComponentsUtil usage completed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar
HI Catarine,
Could you please help me scan this pull?
Thank you!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@julschong a regression found:

`PortalImplCanonicalURLTest`
```
com.liferay.portal.util.test.PortalImplCanonicalURLTest > testCanonicalURLWithFriendlyURL FAILED
    org.junit.ComparisonFailure: expected:<...s4d2z/-/content-name[?_ga=2.237928582.786466685.1515402734-1365236376]> but was:<...s4d2z/-/content-name[]>
    	at org.junit.Assert.assertEquals(Assert.java:117)
    	at org.junit.Assert.assertEquals(Assert.java:146)
    	at com.liferay.portal.util.test.PortalImplCanonicalURLTest.testCanonicalURLWithFriendlyURL(PortalImplCanonicalURLTest.java:274)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-37/test-portal-acceptance-pullrequest(master)/2785/modules-integration-mysql57-jdk8/3/6/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, would you please help me scan this test result again?
thank you!

**Comment by vicnate5** [comment]
@julschong Just a semver issue here, no regressions found.
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MAJOR      37.0.0     37.0.0     38.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.kernel.util.HttpComponentsUtil
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,boolean)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,double)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,int)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,java.lang.String)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     addParameter(java.lang.String,java.lang.String,short)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     removeParameter(java.lang.String,java.lang.String)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,boolean)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,double)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,int)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,java.lang.String)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     setParameter(java.lang.String,java.lang.String,short)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 59.0.0
```

**Comment by julschong** [comment]
rebase and push semver commit

**Comment by julschong** [comment]
rebased and converted some newly added HttpComponentsUtil.addParameter usages

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
submit to core

**Pull request closed without merging**
