### PR TITLE
LPS-151632 test Remove petra-portlet-url-builder

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me scan this test result?
Thank you!

**Comment by vicnate5** [comment]
@julschong Unique failure in unit test [LibraryReferenceTest](https://testray.liferay.com/reports/production/logs/2022-06/test-1-38/test-portal-acceptance-pullrequest(master)/1794/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
```
    [junit] Running com.liferay.portal.library.LibraryReferenceTest
    [junit] Testsuite: com.liferay.portal.library.LibraryReferenceTest
    [junit] Tests run: 14, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 4.145 sec
    [junit] Tests run: 14, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 4.145 sec
    [junit] 
    [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-portlet-url-builder]
    [junit] junit.framework.AssertionFailedError: util-bridges/util-bridges.iml is missing orderEntry elements for modules [portal-portlet-url-builder]
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
    [junit] 
    [junit] 
    [junit] Testcase: testModulesSourceDirsInNetBeans(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] nbproject/project.xml is missing a reference to modules/apps/portal/portal-portlet-url-builder/src/main/java
    [junit] junit.framework.AssertionFailedError: nbproject/project.xml is missing a reference to modules/apps/portal/portal-portlet-url-builder/src/main/java
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testMissingModuleSourceDirReferences(LibraryReferenceTest.java:262)
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testModulesSourceDirsInNetBeans(LibraryReferenceTest.java:189)
    [junit] 
    [junit] 
    [junit] Testcase: testEclipseSourceDirsInModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] .classpath has a nonexistent reference to modules/apps/petra/petra-portlet-url-builder/src/main/java
    [junit] junit.framework.AssertionFailedError: .classpath has a nonexistent reference to modules/apps/petra/petra-portlet-url-builder/src/main/java
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testNonexistentModuleSourceDirReferences(LibraryReferenceTest.java:288)
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testEclipseSourceDirsInModules(LibraryReferenceTest.java:100)
    [junit] 
    [junit] 
    [junit] Testcase: testModulesSourceDirsInEclipse(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] .classpath is missing a reference to modules/apps/portal/portal-portlet-url-builder/src/main/java
    [junit] junit.framework.AssertionFailedError: .classpath is missing a reference to modules/apps/portal/portal-portlet-url-builder/src/main/java
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testMissingModuleSourceDirReferences(LibraryReferenceTest.java:262)
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testModulesSourceDirsInEclipse(LibraryReferenceTest.java:183)
    [junit] 
    [junit] 
    [junit] Testcase: testNetBeansSourceDirsInModules(com.liferay.portal.library.LibraryReferenceTest):	FAILED
    [junit] nbproject/project.xml has a nonexistent reference to modules/apps/petra/petra-portlet-url-builder/src/main/java
    [junit] junit.framework.AssertionFailedError: nbproject/project.xml has a nonexistent reference to modules/apps/petra/petra-portlet-url-builder/src/main/java
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testNonexistentModuleSourceDirReferences(LibraryReferenceTest.java:288)
    [junit] 	at com.liferay.portal.library.LibraryReferenceTest.testNetBeansSourceDirsInModules(LibraryReferenceTest.java:201)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.library.LibraryReferenceTest FAILED
```

**Comment by julschong** [comment]
resolve conflict in usages and fix LibraryReferenceTest

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
submit to core

**Pull request closed without merging**
