### PR TITLE
LPS-143631 test JSONFactoryUtil fixing lpkg error

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, 
I think I finally fixed the error from https://github.com/liferay-core-infra/liferay-portal/pull/804#issuecomment-1135235049
could you please help me double check on this?
Thank you!!

**Comment by catarineaguiar** [comment]
Hi @julschong, code conflicts, rebase please.

The lpkg error seems to be fixed, but according to relevant analysis this failure happened:

`SearchDisplayContextTest`
```
com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest > testNoScopeParameter FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.web.internal.display.context.SearchDisplayContext
        at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest._createSearchDisplayContext(SearchDisplayContextTest.java:271)
        at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest._assertSearchKeywords(SearchDisplayContextTest.java:154)
        at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest.testNoScopeParameter(SearchDisplayContextTest.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/847/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed to resolve many conflicts so test ci test just in case

**Comment by julschong** [comment]
> Hi @julschong, code conflicts, rebase please.
> 
> The lpkg error seems to be fixed, but according to relevant analysis this failure happened:
> 
> `SearchDisplayContextTest`
> 
> ```
> com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest > testNoScopeParameter FAILED
>     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.web.internal.display.context.SearchDisplayContext
>         at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest._createSearchDisplayContext(SearchDisplayContextTest.java:271)
>         at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest._assertSearchKeywords(SearchDisplayContextTest.java:154)
>         at com.liferay.portal.search.web.internal.display.context.SearchDisplayContextTest.testNoScopeParameter(SearchDisplayContextTest.java:100)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/847/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

@catarineaguiar I could not get this error in my local machine

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:lpkg

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
rebase for conflict for: 

> modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMIndexerImpl.java

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
