### PR TITLE
LPS-152081 test mail sender

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
fixed code and pushed again

**Comment by julschong** [comment]
ci:test:Sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
added some missing changes

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help us scan the test result again just in case?
Thank you!

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@julschong,
There is an upgrade issue on this PR that causes most of the upgrade tests to fail before they ran. I am currently building a bundle off the PR so that I can test locally. While waiting for the bundle, here is information about the issue.

https://testray.liferay.com/home/-/testray/case_results/1713210478

https://testray.liferay.com/reports/production/logs/2022-04/test-1-25/test-portal-acceptance-pullrequest(master)/2595/functional-upgrade-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0

`2022-04-28 20:14:18.364 ERROR [main][DBUpgrader:79] null
     [java] java.lang.RuntimeException: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [META-INF/mail-spring.xml]; nested exception is java.io.FileNotFoundException: class path resource [META-INF/mail-spring.xml] cannot be opened because it does not exist
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:289) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:209) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:119) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [META-INF/mail-spring.xml]; nested exception is java.io.FileNotFoundException: class path resource [META-INF/mail-spring.xml] cannot be opened because it does not exist
     [java] 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:638) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:272) ~[portal-impl.jar:?]
     [java] 	... 7 more
     [java] Caused by: java.io.FileNotFoundException: class path resource [META-INF/mail-spring.xml] cannot be opened because it does not exist
     [java] 	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199) ~[spring-core.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:333) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[spring-beans.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:638) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context.jar:5.2.20.RELEASE]
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:272) ~[portal-impl.jar:?]
     [java] 	... 7 more`

Thanks!

**Comment by koor4356** [comment]
@julschong 
I was able to confirm this locally. 
- Use the attached upgrade data to populate the database
- Run upgrade
The above error was thrown.
[data-archive-portal-mysql.zip](https://github.com/julschong/liferay-portal/files/8595189/data-archive-portal-mysql.zip)

**Comment by julschong** [comment]
found a reference to mail-spring.xml in portal.properties that I didnt remove. Pushed and test again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:bundle

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by vicnate5** [comment]
@julschong No regressions found.

**Pull request closed without merging**
