### PR TITLE
[Test Fix] LPD-22758 Fix NewEnvJVMTestRule so that New JVM would use the same java as the current environment, not the system default

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by regiCesar21** [comment]
ci:report:2565652644

**Comment by regiCesar21** [comment]
ci:report:2565647591

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:jdk21-unit

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:jdk21-unit

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2567891798

**Comment by julschong** [comment]
ci:report:2568285154

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
