### PR TITLE
LPS-149331 Remove unused packages in analytics modules

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle, 
This PR is just removing some packages in analytics app module. I'm not very sure what other files I need to remove.
Could you please help me check on it?
Thank you!

**Comment by bronsonsoda** [comment]
@julschong no regressions found

@vicnate5

**Pull request closed without merging**
