### PR TITLE
LPS-142626 testing ci:test:sf

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@hhuijser 
Hi Hugo,
I ran into an odd issue here. on line 144 I used PortalClassPathUtil::_filterPetraJar to pass in a function.
Tested locally but failed ci:test:sf. When I changed it to use lambda function instead, ci:test:sf passed.

Could you please help me investigate on this?
Thanks!

**Comment by julschong** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@julschong sorry, only see this pull now.
Looks like sf passed? https://github.com/julschong/liferay-portal/pull/17#issuecomment-998125382

What did SF complain about when it failed for you?

**Comment by julschong** [comment]
@hhuijser
No worries :D
it went away on the next day and I honestly do not remember what was the exact problem was.

**Pull request closed without merging**
