### PR TITLE
LPS-156316 test removing blocking from PortalCacheManager

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, 
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-cache/portal-cache-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.cache                           MAJOR      4.0.0      4.0.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.portal.cache.BasePortalCacheManager
     [exec]     		+   method     getPortalCache(java.lang.String,boolean)
     [exec]     			+   return     com.liferay.portal.kernel.cache.PortalCache
     [exec]     		-   method     getPortalCache(java.lang.String,boolean,boolean)
     [exec]     			-   return     com.liferay.portal.kernel.cache.PortalCache
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-38/test-portal-acceptance-pullrequest(master)/1604/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

*I'm waiting acceptance results.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
> @catarineaguiar Hi Cararine, when I run ant all, only portal kernel semantic versioning would update. not portal-cache. I can manually change the version up, but is there another command to update them?

Hi @julschong, I don't know how to answer that, maybe @vicnate5 knows

**Comment by catarineaguiar** [comment]
Any regression found on acceptance.

**Pull request closed without merging**
