### PR TITLE
LPS-146041 JavaOSGiReferenceCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Julius,

I make this pull just because QA team has's been spotted SF issues on 7.x yesterday and opened tickets for that.

I moved all `serviceReferenceUtilClassNames` from `sourcechecks.xml `to `source-formatter.properties`(master) so that we can apply this to master only.

Can you help to check if we need to apply some of them to 7.x? If yes, you can add them to `source-formatter.properties`(each branch)

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
um, we should add some Util classes to 7.x, looks like only 3 or 4 Util classes you added last week cause SF issues on 7.x.
@julschong can you help add them to `source-formatter.properties` for 7.x?

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by julschong** [comment]
Please see https://issues.liferay.com/browse/LPS-146041

**Pull request closed without merging**
