### PR TITLE
LPS-151723 Revert git-commit/liferay-release-tool-ee back to Head

### PR DESCRIPTION
**Pull request by julschong**
This is to revert git-commit/liferay-release-tool-ee back to HEAD.
CC. @tinatian

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:license

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
I killed the default test run here since we don't need it for this change.

**Comment by vicnate5** [comment]
@julschong The license test passed here

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
