### PR TITLE
LPS-142279

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:help

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
@kyle-miho Hi Kyle,
This pull refactored and changed a method that was using conditions for different Server types. 
Could you please help me check the test results?

**Comment by kyle-miho** [comment]
ci:test

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
@julschong wanted to make sure you know the failures are related, there semantic versioning issues with the PR, could you fix it when you have a chance?

**Comment by julschong** [comment]
@kyle-miho Jeff and I seem to be running into the same issue this time. we run ant all but the package.info version isn't upreved

**Pull request closed without merging**
