### PR TITLE
test mulesoft

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@vicnate5 Hi Victor,
I made some changes to modules/etl/mulesoft. Is there anyway we can test it on ci? relevant doesn't seem to find much to test. I tried running `mvn test` locally but it failed :|

**Comment by vicnate5** [comment]
@victoroscuro Is there any automation for Mulesoft connector we can run?

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@vicnate5 mulesoft connector integration is a Data Integration feature which now is part of the headless team. 
There are test suites running specific tests for DI but I don't recall any functional test covering it, @Kvale1733 could help with this and I don't know whether there are integration tests on this. @magjed4289 could you please help us figure out if there's any coverage? Thanks

**Comment by magjed4289** [comment]
I contacted a developer to give more details on the integration. I can create an issue to try adding the tests to the relevant, once the dev confirmes they're valid.

**Comment by Kvale1733** [comment]
@vicnate5 Hey Victor. I don't know if there are any tests covering this. I only wrote tests for the Import / Export feature when I was working with Di.

**Comment by vicnate5** [comment]
We will just need to run the tests that are in the module, doesn't look like we have any functional tests to execute for this.

**Comment by magjed4289** [comment]
@vicnate5 is the relevant stuck here? 🤔

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Asking CI team for help with relevant here.

**Comment by vicnate5** [comment]
The tests for modules/etl are disabled on Relevant (maybe they don't work on CI?).

I tried enabling them here and will see what happens
https://github.com/julschong/liferay-portal/pull/731

**Comment by vicnate5** [comment]
I wasn't able to do a temp modification to ci.properties. @julschong Are you still unable to run the tests locally?

**Comment by julschong** [comment]
@vicnate5 Hi Victor,

**Comment by julschong** [comment]
@vicnate5 @magjed4289 @Kvale1733 
Just ran unit test with `mvn test`
it worked locally. I will resubmit this to core,

**Pull request closed without merging**
