### PR TITLE
LPS-143420

### PR DESCRIPTION
**Pull request by julschong**
Hello, @tinatian @shuyangzhou
this is to rebase again and submit from brianchandotcom#111777 -> [brianchandotcom#111824](https://github.com/brianchandotcom/liferay-portal/pull/111824)

### CODE REVIEW

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@koor4356 Hi Koor,
Could you please help me check if my code is the one causing sf to not pass?

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
@julschong 
I believe your code made some changes to SF.  SF is not failing anywhere else. So this source formatting is caused by your code. Please take a look. Thanks!

`java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./portal-impl/src/com/liferay/portal/upgrade/PortalUpgradeProcess.java
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:345)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:249)
     [java] Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./portal-impl/src/com/liferay/portal/upgrade/PortalUpgradeProcess.java
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:119)
     [java] 	at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:1161)
     [java] 	at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:73)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:331)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:327)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.RuntimeException: Unable to format ./portal-impl/src/com/liferay/portal/upgrade/PortalUpgradeProcess.java
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:716)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:74)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:108)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:104)
     [java] 	... 4 more
     [java] Caused by: java.lang.ExceptionInInitializerError
     [java] 	at java.lang.Class.forName0(Native Method)
     [java] 	at java.lang.Class.forName(Class.java:264)
     [java] 	at com.liferay.source.formatter.checks.JavaMapBuilderGenericsCheck._getClass(JavaMapBuilderGenericsCheck.java:134)
     [java] 	at com.liferay.source.formatter.checks.JavaMapBuilderGenericsCheck._formatGenerics(JavaMapBuilderGenericsCheck.java:86)
     [java] 	at com.liferay.source.formatter.checks.JavaMapBuilderGenericsCheck.doProcess(JavaMapBuilderGenericsCheck.java:46)
     [java] 	at com.liferay.source.formatter.checks.BaseJavaTermCheck._walkJavaClass(BaseJavaTermCheck.java:203)
     [java] 	at com.liferay.source.formatter.checks.BaseJavaTermCheck.process(BaseJavaTermCheck.java:46)
     [java] 	at com.liferay.source.formatter.checks.util.SourceChecksUtil._processJavaTermCheck(SourceChecksUtil.java:380)
     [java] 	at com.liferay.source.formatter.checks.util.SourceChecksUtil.processSourceChecks(SourceChecksUtil.java:156)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._processSourceChecks(BaseSourceProcessor.java:727)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:314)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:275)
     [java] 	at com.liferay.source.formatter.JavaSourceProcessor.format(JavaSourceProcessor.java:72)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:602)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:704)
     [java] 	... 7 more
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.util.PropsUtil.get(PropsUtil.java:31)
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.<clinit>(BaseDBProcess.java:364)
     [java] 	... 22 more`

**Comment by julschong** [comment]
@koor4356 Thanks Koor, I'll check again

**Pull request closed without merging**
