### PR TITLE
LPS-155670 test removing getLibDir method

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
could you please help me scan the result when its completed?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
 [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/57.0.0/14755719a5bbfa0f90597595fb414d44d9d5e6e3/com.liferay.portal.kernel-57.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-35/test-portal-acceptance-pullrequest(master)/1739/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@catarineaguiar I'm going to submit to core, looks ok to me at a glance :)

**Pull request closed without merging**
