### PR TITLE
LPD-X test JDK21 as default jdk

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by julschong** [comment]
ci:report:48704391

**Comment by julschong** [comment]
ci:test:upstream-dxp

**Comment by julschong** [comment]
ci:stop

**Comment by vicnate5** [comment]
@julschong We can trigger the bigger suite at the end of the day.

how are the current results looking?

**Comment by julschong** [comment]
image
not bad
and no batches failed entirely on https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6885/jenkins-report.html

**Pull request closed without merging**
