### PR TITLE
LPS-152300 test removing petra-salesforce-client

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help us scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Pull request closed without merging**
